name: fetchingburulasapi
description: Fetching Burulas API.
publish_to: 'none'
version: 1.3.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.3.0
  sliding_up_panel: ^2.0.0+1
  flutter_launcher_icons: ^0.14.3
  contained_tab_bar_view: ^0.8.0
  collection:
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  mockito: ^5.4.5
  flutter_map_marker_popup: ^8.0.1
  google_fonts: ^6.2.1


dev_dependencies:
  test: ^1.25.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/models/search/
