# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      # Run your commands
      - name: Run Dart commands
        run: |
          flutter pub get
          flutter run
